// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/fixture_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFixtureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fixture *Fixture `protobuf:"bytes,1,opt,name=fixture,proto3" json:"fixture,omitempty"`
}

func (x *CreateFixtureRequest) Reset() {
	*x = CreateFixtureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fixture_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFixtureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFixtureRequest) ProtoMessage() {}

func (x *CreateFixtureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fixture_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFixtureRequest.ProtoReflect.Descriptor instead.
func (*CreateFixtureRequest) Descriptor() ([]byte, []int) {
	return file_proto_fixture_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFixtureRequest) GetFixture() *Fixture {
	if x != nil {
		return x.Fixture
	}
	return nil
}

type CreateFixtureResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateFixtureResponse) Reset() {
	*x = CreateFixtureResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fixture_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFixtureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFixtureResponse) ProtoMessage() {}

func (x *CreateFixtureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fixture_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFixtureResponse.ProtoReflect.Descriptor instead.
func (*CreateFixtureResponse) Descriptor() ([]byte, []int) {
	return file_proto_fixture_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFixtureResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SearchFixtureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter *Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *SearchFixtureRequest) Reset() {
	*x = SearchFixtureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fixture_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchFixtureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFixtureRequest) ProtoMessage() {}

func (x *SearchFixtureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fixture_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFixtureRequest.ProtoReflect.Descriptor instead.
func (*SearchFixtureRequest) Descriptor() ([]byte, []int) {
	return file_proto_fixture_service_proto_rawDescGZIP(), []int{2}
}

func (x *SearchFixtureRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type SearchFixtureResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fixture *Fixture `protobuf:"bytes,1,opt,name=fixture,proto3" json:"fixture,omitempty"`
}

func (x *SearchFixtureResponse) Reset() {
	*x = SearchFixtureResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fixture_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchFixtureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFixtureResponse) ProtoMessage() {}

func (x *SearchFixtureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fixture_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFixtureResponse.ProtoReflect.Descriptor instead.
func (*SearchFixtureResponse) Descriptor() ([]byte, []int) {
	return file_proto_fixture_service_proto_rawDescGZIP(), []int{3}
}

func (x *SearchFixtureResponse) GetFixture() *Fixture {
	if x != nil {
		return x.Fixture
	}
	return nil
}

var File_proto_fixture_service_proto protoreflect.FileDescriptor

var file_proto_fixture_service_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x66,
	0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x73, 0x1a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66,
	0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x43, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x78, 0x74, 0x75, 0x72,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x07, 0x66, 0x69, 0x78, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x66, 0x69, 0x78, 0x74,
	0x75, 0x72, 0x65, 0x73, 0x2e, 0x46, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x52, 0x07, 0x66, 0x69,
	0x78, 0x74, 0x75, 0x72, 0x65, 0x22, 0x27, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46,
	0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x40,
	0x0a, 0x14, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x66, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65,
	0x73, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x22, 0x44, 0x0a, 0x15, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x69, 0x78, 0x74, 0x75, 0x72,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x66, 0x69, 0x78,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x66, 0x69, 0x78,
	0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x46, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x52, 0x07, 0x66,
	0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x32, 0xba, 0x01, 0x0a, 0x0e, 0x46, 0x69, 0x78, 0x74, 0x75,
	0x72, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x52, 0x0a, 0x0d, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x46, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1e, 0x2e, 0x66, 0x69, 0x78,
	0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x78, 0x74,
	0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x66, 0x69, 0x78,
	0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x78, 0x74,
	0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54, 0x0a,
	0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1e,
	0x2e, 0x66, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x46, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x66, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x46, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x30, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_fixture_service_proto_rawDescOnce sync.Once
	file_proto_fixture_service_proto_rawDescData = file_proto_fixture_service_proto_rawDesc
)

func file_proto_fixture_service_proto_rawDescGZIP() []byte {
	file_proto_fixture_service_proto_rawDescOnce.Do(func() {
		file_proto_fixture_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_fixture_service_proto_rawDescData)
	})
	return file_proto_fixture_service_proto_rawDescData
}

var file_proto_fixture_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_fixture_service_proto_goTypes = []interface{}{
	(*CreateFixtureRequest)(nil),  // 0: fixtures.CreateFixtureRequest
	(*CreateFixtureResponse)(nil), // 1: fixtures.CreateFixtureResponse
	(*SearchFixtureRequest)(nil),  // 2: fixtures.SearchFixtureRequest
	(*SearchFixtureResponse)(nil), // 3: fixtures.SearchFixtureResponse
	(*Fixture)(nil),               // 4: fixtures.Fixture
	(*Filter)(nil),                // 5: fixtures.Filter
}
var file_proto_fixture_service_proto_depIdxs = []int32{
	4, // 0: fixtures.CreateFixtureRequest.fixture:type_name -> fixtures.Fixture
	5, // 1: fixtures.SearchFixtureRequest.filter:type_name -> fixtures.Filter
	4, // 2: fixtures.SearchFixtureResponse.fixture:type_name -> fixtures.Fixture
	0, // 3: fixtures.FixtureService.CreateFixture:input_type -> fixtures.CreateFixtureRequest
	2, // 4: fixtures.FixtureService.SearchFixture:input_type -> fixtures.SearchFixtureRequest
	1, // 5: fixtures.FixtureService.CreateFixture:output_type -> fixtures.CreateFixtureResponse
	3, // 6: fixtures.FixtureService.SearchFixture:output_type -> fixtures.SearchFixtureResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_fixture_service_proto_init() }
func file_proto_fixture_service_proto_init() {
	if File_proto_fixture_service_proto != nil {
		return
	}
	file_proto_fixture_message_proto_init()
	file_proto_filter_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_fixture_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFixtureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fixture_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFixtureResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fixture_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchFixtureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fixture_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchFixtureResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_fixture_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fixture_service_proto_goTypes,
		DependencyIndexes: file_proto_fixture_service_proto_depIdxs,
		MessageInfos:      file_proto_fixture_service_proto_msgTypes,
	}.Build()
	File_proto_fixture_service_proto = out.File
	file_proto_fixture_service_proto_rawDesc = nil
	file_proto_fixture_service_proto_goTypes = nil
	file_proto_fixture_service_proto_depIdxs = nil
}
