// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/scores_message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Score struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Localteam string `protobuf:"bytes,1,opt,name=localteam,proto3" json:"localteam,omitempty"`
	Awayteam  string `protobuf:"bytes,2,opt,name=awayteam,proto3" json:"awayteam,omitempty"`
	Htscore   string `protobuf:"bytes,3,opt,name=htscore,proto3" json:"htscore,omitempty"`
	Ftscore   string `protobuf:"bytes,4,opt,name=ftscore,proto3" json:"ftscore,omitempty"`
}

func (x *Score) Reset() {
	*x = Score{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scores_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Score) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Score) ProtoMessage() {}

func (x *Score) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scores_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Score.ProtoReflect.Descriptor instead.
func (*Score) Descriptor() ([]byte, []int) {
	return file_proto_scores_message_proto_rawDescGZIP(), []int{0}
}

func (x *Score) GetLocalteam() string {
	if x != nil {
		return x.Localteam
	}
	return ""
}

func (x *Score) GetAwayteam() string {
	if x != nil {
		return x.Awayteam
	}
	return ""
}

func (x *Score) GetHtscore() string {
	if x != nil {
		return x.Htscore
	}
	return ""
}

func (x *Score) GetFtscore() string {
	if x != nil {
		return x.Ftscore
	}
	return ""
}

var File_proto_scores_message_proto protoreflect.FileDescriptor

var file_proto_scores_message_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x66, 0x69,
	0x78, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0x75, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x74, 0x65, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x74, 0x65, 0x61, 0x6d, 0x12, 0x1a, 0x0a,
	0x08, 0x61, 0x77, 0x61, 0x79, 0x74, 0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x61, 0x77, 0x61, 0x79, 0x74, 0x65, 0x61, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x74, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x74, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x74, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x74, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x42, 0x09, 0x5a,
	0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_scores_message_proto_rawDescOnce sync.Once
	file_proto_scores_message_proto_rawDescData = file_proto_scores_message_proto_rawDesc
)

func file_proto_scores_message_proto_rawDescGZIP() []byte {
	file_proto_scores_message_proto_rawDescOnce.Do(func() {
		file_proto_scores_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_scores_message_proto_rawDescData)
	})
	return file_proto_scores_message_proto_rawDescData
}

var file_proto_scores_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_scores_message_proto_goTypes = []interface{}{
	(*Score)(nil), // 0: fixtures.Score
}
var file_proto_scores_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_scores_message_proto_init() }
func file_proto_scores_message_proto_init() {
	if File_proto_scores_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_scores_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Score); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_scores_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_scores_message_proto_goTypes,
		DependencyIndexes: file_proto_scores_message_proto_depIdxs,
		MessageInfos:      file_proto_scores_message_proto_msgTypes,
	}.Build()
	File_proto_scores_message_proto = out.File
	file_proto_scores_message_proto_rawDesc = nil
	file_proto_scores_message_proto_goTypes = nil
	file_proto_scores_message_proto_depIdxs = nil
}
