// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/stats_message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Shots struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total  int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Ongoal int32 `protobuf:"varint,2,opt,name=ongoal,proto3" json:"ongoal,omitempty"`
}

func (x *Shots) Reset() {
	*x = Shots{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_stats_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Shots) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shots) ProtoMessage() {}

func (x *Shots) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shots.ProtoReflect.Descriptor instead.
func (*Shots) Descriptor() ([]byte, []int) {
	return file_proto_stats_message_proto_rawDescGZIP(), []int{0}
}

func (x *Shots) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Shots) GetOngoal() int32 {
	if x != nil {
		return x.Ongoal
	}
	return 0
}

type Goals struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scored   int32 `protobuf:"varint,1,opt,name=scored,proto3" json:"scored,omitempty"`
	Assists  int32 `protobuf:"varint,2,opt,name=assists,proto3" json:"assists,omitempty"`
	Conceded int32 `protobuf:"varint,3,opt,name=conceded,proto3" json:"conceded,omitempty"`
	Owngoals int32 `protobuf:"varint,4,opt,name=owngoals,proto3" json:"owngoals,omitempty"`
}

func (x *Goals) Reset() {
	*x = Goals{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_stats_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Goals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goals) ProtoMessage() {}

func (x *Goals) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goals.ProtoReflect.Descriptor instead.
func (*Goals) Descriptor() ([]byte, []int) {
	return file_proto_stats_message_proto_rawDescGZIP(), []int{1}
}

func (x *Goals) GetScored() int32 {
	if x != nil {
		return x.Scored
	}
	return 0
}

func (x *Goals) GetAssists() int32 {
	if x != nil {
		return x.Assists
	}
	return 0
}

func (x *Goals) GetConceded() int32 {
	if x != nil {
		return x.Conceded
	}
	return 0
}

func (x *Goals) GetOwngoals() int32 {
	if x != nil {
		return x.Owngoals
	}
	return 0
}

type Stats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shots []*Shots `protobuf:"bytes,1,rep,name=shots,proto3" json:"shots,omitempty"`
	Goals []*Goals `protobuf:"bytes,2,rep,name=goals,proto3" json:"goals,omitempty"`
}

func (x *Stats) Reset() {
	*x = Stats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_stats_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_proto_stats_message_proto_rawDescGZIP(), []int{2}
}

func (x *Stats) GetShots() []*Shots {
	if x != nil {
		return x.Shots
	}
	return nil
}

func (x *Stats) GetGoals() []*Goals {
	if x != nil {
		return x.Goals
	}
	return nil
}

var File_proto_stats_message_proto protoreflect.FileDescriptor

var file_proto_stats_message_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x66, 0x69, 0x78,
	0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0x35, 0x0a, 0x05, 0x53, 0x68, 0x6f, 0x74, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x6e, 0x67, 0x6f, 0x61, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x6e, 0x67, 0x6f, 0x61, 0x6c, 0x22, 0x71, 0x0a, 0x05,
	0x47, 0x6f, 0x61, 0x6c, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x73, 0x73, 0x69, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x61, 0x73, 0x73, 0x69, 0x73, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x63, 0x65,
	0x64, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x63, 0x65,
	0x64, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x67, 0x6f, 0x61, 0x6c, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6f, 0x77, 0x6e, 0x67, 0x6f, 0x61, 0x6c, 0x73, 0x22,
	0x55, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x25, 0x0a, 0x05, 0x73, 0x68, 0x6f, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x69, 0x78, 0x74, 0x75, 0x72,
	0x65, 0x73, 0x2e, 0x53, 0x68, 0x6f, 0x74, 0x73, 0x52, 0x05, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x12,
	0x25, 0x0a, 0x05, 0x67, 0x6f, 0x61, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x66, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x47, 0x6f, 0x61, 0x6c, 0x73, 0x52,
	0x05, 0x67, 0x6f, 0x61, 0x6c, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_stats_message_proto_rawDescOnce sync.Once
	file_proto_stats_message_proto_rawDescData = file_proto_stats_message_proto_rawDesc
)

func file_proto_stats_message_proto_rawDescGZIP() []byte {
	file_proto_stats_message_proto_rawDescOnce.Do(func() {
		file_proto_stats_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_stats_message_proto_rawDescData)
	})
	return file_proto_stats_message_proto_rawDescData
}

var file_proto_stats_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_stats_message_proto_goTypes = []interface{}{
	(*Shots)(nil), // 0: fixtures.Shots
	(*Goals)(nil), // 1: fixtures.Goals
	(*Stats)(nil), // 2: fixtures.Stats
}
var file_proto_stats_message_proto_depIdxs = []int32{
	0, // 0: fixtures.Stats.shots:type_name -> fixtures.Shots
	1, // 1: fixtures.Stats.goals:type_name -> fixtures.Goals
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_stats_message_proto_init() }
func file_proto_stats_message_proto_init() {
	if File_proto_stats_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_stats_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Shots); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_stats_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Goals); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_stats_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_stats_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_stats_message_proto_goTypes,
		DependencyIndexes: file_proto_stats_message_proto_depIdxs,
		MessageInfos:      file_proto_stats_message_proto_msgTypes,
	}.Build()
	File_proto_stats_message_proto = out.File
	file_proto_stats_message_proto_rawDesc = nil
	file_proto_stats_message_proto_goTypes = nil
	file_proto_stats_message_proto_depIdxs = nil
}
