// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/weather_message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Temp_Unit int32

const (
	Temp_FAHRENHEIT Temp_Unit = 0
	Temp_CELSIUS    Temp_Unit = 1
)

// Enum value maps for Temp_Unit.
var (
	Temp_Unit_name = map[int32]string{
		0: "FAHRENHEIT",
		1: "CELSIUS",
	}
	Temp_Unit_value = map[string]int32{
		"FAHRENHEIT": 0,
		"CELSIUS":    1,
	}
)

func (x Temp_Unit) Enum() *Temp_Unit {
	p := new(Temp_Unit)
	*p = x
	return p
}

func (x Temp_Unit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Temp_Unit) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_weather_message_proto_enumTypes[0].Descriptor()
}

func (Temp_Unit) Type() protoreflect.EnumType {
	return &file_proto_weather_message_proto_enumTypes[0]
}

func (x Temp_Unit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Temp_Unit.Descriptor instead.
func (Temp_Unit) EnumDescriptor() ([]byte, []int) {
	return file_proto_weather_message_proto_rawDescGZIP(), []int{1, 0}
}

type Weather struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Clouds   string `protobuf:"bytes,4,opt,name=clouds,proto3" json:"clouds,omitempty"`
	Temp     *Temp  `protobuf:"bytes,5,opt,name=temp,proto3" json:"temp,omitempty"`
	Wind     *Wind  `protobuf:"bytes,6,opt,name=wind,proto3" json:"wind,omitempty"`
	Humidity string `protobuf:"bytes,7,opt,name=humidity,proto3" json:"humidity,omitempty"`
}

func (x *Weather) Reset() {
	*x = Weather{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_weather_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Weather) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weather) ProtoMessage() {}

func (x *Weather) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weather_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weather.ProtoReflect.Descriptor instead.
func (*Weather) Descriptor() ([]byte, []int) {
	return file_proto_weather_message_proto_rawDescGZIP(), []int{0}
}

func (x *Weather) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Weather) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Weather) GetClouds() string {
	if x != nil {
		return x.Clouds
	}
	return ""
}

func (x *Weather) GetTemp() *Temp {
	if x != nil {
		return x.Temp
	}
	return nil
}

func (x *Weather) GetWind() *Wind {
	if x != nil {
		return x.Wind
	}
	return nil
}

func (x *Weather) GetHumidity() string {
	if x != nil {
		return x.Humidity
	}
	return ""
}

type Temp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Temp float32   `protobuf:"fixed32,1,opt,name=temp,proto3" json:"temp,omitempty"`
	Unit Temp_Unit `protobuf:"varint,2,opt,name=unit,proto3,enum=fixtures.Temp_Unit" json:"unit,omitempty"`
}

func (x *Temp) Reset() {
	*x = Temp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_weather_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Temp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Temp) ProtoMessage() {}

func (x *Temp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weather_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Temp.ProtoReflect.Descriptor instead.
func (*Temp) Descriptor() ([]byte, []int) {
	return file_proto_weather_message_proto_rawDescGZIP(), []int{1}
}

func (x *Temp) GetTemp() float32 {
	if x != nil {
		return x.Temp
	}
	return 0
}

func (x *Temp) GetUnit() Temp_Unit {
	if x != nil {
		return x.Unit
	}
	return Temp_FAHRENHEIT
}

type Wind struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Speed  string `protobuf:"bytes,1,opt,name=speed,proto3" json:"speed,omitempty"`
	Degree int32  `protobuf:"varint,2,opt,name=degree,proto3" json:"degree,omitempty"`
}

func (x *Wind) Reset() {
	*x = Wind{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_weather_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Wind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wind) ProtoMessage() {}

func (x *Wind) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weather_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wind.ProtoReflect.Descriptor instead.
func (*Wind) Descriptor() ([]byte, []int) {
	return file_proto_weather_message_proto_rawDescGZIP(), []int{2}
}

func (x *Wind) GetSpeed() string {
	if x != nil {
		return x.Speed
	}
	return ""
}

func (x *Wind) GetDegree() int32 {
	if x != nil {
		return x.Degree
	}
	return 0
}

var File_proto_weather_message_proto protoreflect.FileDescriptor

var file_proto_weather_message_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x66,
	0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0xad, 0x01, 0x0a, 0x07, 0x57, 0x65, 0x61, 0x74,
	0x68, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x73, 0x12, 0x22, 0x0a, 0x04, 0x74, 0x65, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x54, 0x65, 0x6d,
	0x70, 0x52, 0x04, 0x74, 0x65, 0x6d, 0x70, 0x12, 0x22, 0x0a, 0x04, 0x77, 0x69, 0x6e, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x2e, 0x57, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x77, 0x69, 0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x68,
	0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68,
	0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x22, 0x68, 0x0a, 0x04, 0x54, 0x65, 0x6d, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x65, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x74,
	0x65, 0x6d, 0x70, 0x12, 0x27, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x13, 0x2e, 0x66, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x54, 0x65, 0x6d,
	0x70, 0x2e, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x22, 0x23, 0x0a, 0x04,
	0x55, 0x6e, 0x69, 0x74, 0x12, 0x0e, 0x0a, 0x0a, 0x46, 0x41, 0x48, 0x52, 0x45, 0x4e, 0x48, 0x45,
	0x49, 0x54, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x45, 0x4c, 0x53, 0x49, 0x55, 0x53, 0x10,
	0x01, 0x22, 0x34, 0x0a, 0x04, 0x57, 0x69, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x64, 0x65, 0x67, 0x72, 0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x64, 0x65, 0x67, 0x72, 0x65, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_weather_message_proto_rawDescOnce sync.Once
	file_proto_weather_message_proto_rawDescData = file_proto_weather_message_proto_rawDesc
)

func file_proto_weather_message_proto_rawDescGZIP() []byte {
	file_proto_weather_message_proto_rawDescOnce.Do(func() {
		file_proto_weather_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_weather_message_proto_rawDescData)
	})
	return file_proto_weather_message_proto_rawDescData
}

var file_proto_weather_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_weather_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_weather_message_proto_goTypes = []interface{}{
	(Temp_Unit)(0),  // 0: fixtures.Temp.Unit
	(*Weather)(nil), // 1: fixtures.Weather
	(*Temp)(nil),    // 2: fixtures.Temp
	(*Wind)(nil),    // 3: fixtures.Wind
}
var file_proto_weather_message_proto_depIdxs = []int32{
	2, // 0: fixtures.Weather.temp:type_name -> fixtures.Temp
	3, // 1: fixtures.Weather.wind:type_name -> fixtures.Wind
	0, // 2: fixtures.Temp.unit:type_name -> fixtures.Temp.Unit
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_weather_message_proto_init() }
func file_proto_weather_message_proto_init() {
	if File_proto_weather_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_weather_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Weather); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_weather_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Temp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_weather_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Wind); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_weather_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_weather_message_proto_goTypes,
		DependencyIndexes: file_proto_weather_message_proto_depIdxs,
		EnumInfos:         file_proto_weather_message_proto_enumTypes,
		MessageInfos:      file_proto_weather_message_proto_msgTypes,
	}.Build()
	File_proto_weather_message_proto = out.File
	file_proto_weather_message_proto_rawDesc = nil
	file_proto_weather_message_proto_goTypes = nil
	file_proto_weather_message_proto_depIdxs = nil
}
